package de.elnarion.ddlutils.io;

import de.elnarion.ddlutils.DdlUtilsException;

/**
 * Base class for exceptions generated by DdlUtils when handling XML.
 * 
 * @version $Revision: $
 */
public class DdlUtilsXMLException extends DdlUtilsException
{
    /** Unique id for serialization purposes. */
    private static final long serialVersionUID = 3464139163788952051L;

    /**
     * Creates a new exception object.
     */
    public DdlUtilsXMLException()
    {
        super();
    }

    /**
     * Creates a new exception object.
     * 
     * @param message The exception message
     */
    public DdlUtilsXMLException(String message)
    {
        super(message);
    }

    /**
     * Creates a new exception object.
     * 
     * @param baseEx The base exception
     */
    public DdlUtilsXMLException(Throwable baseEx)
    {
        super(baseEx);
    }

    /**
     * Creates a new exception object.
     * 
     * @param message The exception message
     * @param baseEx  The base exception
     */
    public DdlUtilsXMLException(String message, Throwable baseEx)
    {
        super(message, baseEx);
    }
}
